### ISSUE TITLE
Too Many Castles Around The Map

### ISSUE THREAD

**Issue by ghost** [TheXFactor117/Lost-Eclipse-Outdated#3]
using also biomes o plenty. there are many castles, it is not cool. they should be very rare. now i have to delete this mod until this issue fixed. thanks

**Comment by TheXFactor117** [comment]
Thanks for the report. I will say that issues like these might arise more than with other mods. I'm working on tweaking things like this, and I am also going to add in a config option to change the spawn rates and such. This will be fixed in pre-a1.0.1

**Comment by ghost** [comment]
thanks a lot

**Comment by TheXFactor117** [comment]
Spawn chance has been tweaked. A Config file has also been made, in which you can adjust it if it is still too high or low - we will also try and balance that out too.

Will be implemented in pre-a1.1.0, which will be released soon.

**Comment by ghost** [comment]
okay, waiting for the update. thanks a lot!

**Comment by ghost** [comment]
but i think it is a problem. just look at this, there are really too many castles around the map.
![2017-02-18_22 25 47](https://cloud.githubusercontent.com/assets/24831406/23096642/597b530c-f629-11e6-938f-bf6f11de2ff6.png)

**Comment by ghost** [comment]
but hopefully, i fixed it in the config file. thank you for adding config ^^

**Comment by ghost** [comment]
omg, there is an other problem. i opened 5 new worlds, searched for any castle, couldn't find ANY, and created 6. world, searched for a castle for 15 minutes, then found this:
![2017-02-18_23 11 01](https://cloud.githubusercontent.com/assets/24831406/23096916/bdde9308-f62f-11e6-8fcc-9f3738e4bc6f.png)

what do you think? i really wonder what is the problem. The spawn chance of castles is still 200. because when i make it more than 200, i can't find any.

**Comment by TheXFactor117** [comment]
I guess there is a chance that could happen. One castle spawned on one chunk while the other spawned in the next chunk. I'm going to have to play around with these values a lot though, and clean up structure gen anyways. Feedback like yours is very helpful.

**Comment by ghost** [comment]
I will help as much as i can

**Comment by TheXFactor117** [comment]
Awesome! I will through this out, but if you are interested in becoming more of a "permanent" tester, you could certainly become the first one. Of course, you certainly don't need too. And by permanent, you could obviously stop whenever you want.

**Comment by ghost** [comment]
Okay i will test it tomorrow but please know that i am using other mods too. Like biomes o plenty, ruins, geographicraft....etc. I made a modpack. If you want me test it with only vanilla, ok i will but it would be nice to compatible with other mods. And i think this spawn problem is about biomes/biome types.

**Comment by TheXFactor117** [comment]
Keep mods installed, that's perfectly fine. Also, if you have a Discord, [consider joining Lost Eclipse's server](https://discord.gg/pUfTJFp).
